interface AttributeNameClashWithConstant {
  const boolean right = false;
  attribute DOMString right;
};

interface AttributeNameClashWithOperation {
  void right();
  attribute boolean right;
};

interface AttributeNameClashWithAttribute {
  attribute boolean right;
  attribute DOMString right;
};

interface ValidAttribute {
  attribute boolean right;
  readonly attribute double size;
  stringifier attribute DOMString displayName;
};