callback interface InvalidCallbackInheritance : HTMLElement {
};

interface InvalidNonCallbackInheriantce : InvalidCallbackInheritance {
};

callback interface InvalidStaticAttribute {
  static attribute DOMString name;
};

callback interface InvalidStaticOperation {
  static double getValue();
};
