callback interface InvalidCallbackInheritance : HTMLElement {
  double getValue();
  attribute DOMString name;
};

interface InvalidNonCallbackInheriantce : InvalidCallbackInheritance {
};

callback interface InvalidStaticAttribute {
  static attribute DOMString name;
};

callback interface InvalidStaticOperation {
  attribute DOMString name;
  static double getValue();
};

callback interface InvalidSingleOperation {
  double getValue();
};
