/* bogus usage of Constructor on an attribute */
interface BogusConstructorEAOnAttribute {
  [Constructor] attribute double r;
}; 

/* Valid usage of constructor */
[Constructor,
 Constructor(double radius)]
interface Circle {
  attribute double r;
  attribute double cx;
  attribute double cy;
  readonly attribute double circumference;
};

[Constructor]
dictionary Bundle {
};