dictionary ClashingDictionaryMembers {
  DOMString? fillPattern = "black";
  unsigned short fillPattern;
};

interface InvalidDictionaryAsAttribute {
  attribute ValidDictionary dict;
};

interface ValidDictionaryAsArgument {
  void paintCar(ValidDictionary paint);
};

dictionary ValidDictionary {
  DOMString? fillPattern = "black";
  DOMString? strokePattern = null;
  ValidDictionaryAsArgument position;
};
