// New exceptions should be avoided, except if additional fields are needed
exception RedundantException {
  DOMString name;
  unsigned short code;
};

exception AnotherRedundantException {
  DOMString name;
};

exception AnotherAnotherRedundantException {
};

// Clash with ECMAScript
exception URIError {
};

exception ANonRedundantException {
  DOMString foo;
};