interface Base {
  readonly attribute DOMString name;
  attribute DOMString writableAttr;
};

interface InheritsGetterOnReadOnlyAttribute : Base {
  inherit readonly attribute DOMString name;
};

interface InheritsGetterOnStaticAttribute : Base {
  static inherit attribute DOMString name;
};


interface InheritsGetterOnInheritedNonReadonlAttribute : Base {
  inherit attribute DOMString writableAttr;
};

interface InheritsGetterOnInterfaceWithoutInheritance  {
  inherit attribute DOMString name;
};

interface InheritsGetterWithIncompatibleType : Base  {
  inherit attribute double name;
};

interface ValidInheritsGetter : Base {
  inherit attribute DOMString name;
};
