interface Base {
  readonly attribute DOMString name;
};

interface InheritsGetterOnNonReadOnlyAttribute : Base {
  inherit attribute DOMString name;
};

interface InheritsGetterOnInterfaceWithoutInheritance  {
  inherit readonly attribute DOMString name;
};

interface InheritsGetterWithIncompatibleType : Base  {
  inherit readonly attribute float name;
};

interface ValidInheritsGetter : Base {
  inherit readonly attribute DOMString name;
};
