// [LegacyArrayClass] used on dictionary
[LegacyArrayClass] dictionary BogusArrayClassOnDictionary {
};


// [LegacyArrayClass] used on interface with inheritance
interface Foo {};
[LegacyArrayClass]
interface BogusArrayClassOnInterfaceWithInheritance : Foo {
};

// Valid usage
[LegacyArrayClass]
interface ImmutableItemList {
  readonly attribute unsigned long length;
  getter object getItem(unsigned long index);
};
