interface InvalidLenientThisOnOperation {
  [LenientThis] DOMString foo();
};


interface InvalidLenientThisWithArgument {
  [LenientThis=foo] attribute DOMString x;
};

interface ValidLenientThis {
  [LenientThis] attribute DOMString x;
};