interface NameA {};
// clashes
dictionary NameA {};
typedef DOMString[] NameA;
interface NameA {};

// no clash
dictionary NameC {};
typedef DOMString[] NameD;
interface NameF {};
partial interface NameF{};
