interface NonSpecialOperationWithoutIdentifier {
  DOMString();
};

interface OperationNameClashWithConstant {
  const boolean right = false;
  DOMString right();
};

interface OperationNameClashWithAttribute {
  attribute boolean right;
  DOMString right();
};

interface OperationWithNonLastVariadicArgument {
  double multiply(double... numbers, double factor);
}; 

interface OperationWithVariadicOptionalArgument {
  double multiply(optional double... numbers);
}; 


interface OperationWithOptionalArgumentInMiddle {
  double multiply(optional double number, double number2);
};

interface ValidOperations {
  stringifier DOMString();
  getter DOMString(DOMString name);
  DOMString right(DOMString input);
  boolean right();
  double multipy(double... numbers);
  double factorize(double number, optional double number2, optional double number3);
  double factorize2(double number, optional double number2, double... numbers);
};