interface TwoOperationsWithSameSignature {
  boolean right(DOMString arg);
  boolean right(DOMString param);
};

interface MyType {};
interface MyType2 {};

interface TwoOperationsWithUndistinguishableSingleParam {
  boolean right(double arg);
  boolean right(boolean arg);
};

interface TwoOperationsWithUndistinguishableSingleParam2 {
  boolean right(double? arg);
  boolean right(DOMString? arg);
};

interface TwoOperationsWithUndistinguishableSingleParam3 {
  boolean right(double? arg);
  boolean right(MyType arg);
};


interface TwoOperationsWithUndistinguishableSingleParam4 {
  boolean right(double arg);
  boolean right(DOMString arg);
};

interface TwoOperationsWithUndistinguishableSingleParam5 {
  boolean right(MyType arg);
  boolean right(MyType arg);
};


interface TwoOperationsWithUndistinguishableTwoParams {
  boolean right(double arg, DOMString? str);
  boolean right(boolean arg, MyType t);
};

interface TwoOperationsWithUndistinguishableOptionalParam {
  boolean right(double arg, optional DOMString str);
  boolean right(boolean arg);
};

interface TwoOperationsWithUndistinguishableVariadicParam {
  boolean right(double arg, optional DOMString str);
  boolean right(boolean arg, DOMString str, double... param);
};

interface TwoCallersWithUndistinguishableParam {
  legacycaller boolean foo(double arg);
  legacycaller boolean bar(boolean arg);
};

[NamedConstructor=Right(double arg),
 NamedConstructor=Right(boolean arg)]
interface NamedConstructorWithUndistinguishableParam {
};

[Constructor(double arg),
 Constructor(boolean arg)]
interface ConstructorWithUndistinguishableParam {
};

interface ValidOverloading {
  /* f1 */ void f(DOMString a);
  /* f2 */ void f(DOMString a, DOMString b, double... c);
  /* f3 */ void f();
  /* f4 */ void f(long a, DOMString b, optional DOMString c, double... d);
  void f(object a, DOMString b);
  void f(MyType2 a);
};