// unknown interface UnknowInterface
partial interface UnknowInterface {
};

partial interface Foo : Base {
};

interface Base {
};

[ImplicitThis]
partial interface Foo {
};
// Valid partial interface definition
interface Foo {
};

partial interface Foo {
};
