// unknown interface UnknowInterface
partial interface UnknowInterface {
};

partial interface Foo : Base {
};

interface Base {
};
// Valid partial interface definition
interface Foo {
};

partial interface Foo {
};
