// Invalid usage
[ReplaceableNamedProperties=foo]
interface InvalidReplacedNamedPropertiesExtendedAttributeWithArgument {
  getter any (DOMString name);
};

[ReplaceableNamedProperties]
dictionary InvalidReplacedNamedPropertiesExtendedAttributeUsedOnDictionary {
};

[ReplaceableNamedProperties]
interface InvalidReplacedNamedPropertiesExtendedAttributeUsedWithASetter {
  getter any (DOMString name);
  setter void (DOMString propertyName, float propertyValue);
};

[ReplaceableNamedProperties, OverrideBuiltins]
interface InvalidReplacedNamedPropertiesExtendedAttributeUsedWithOverrideBuiltins {
  getter any (DOMString name);
};


// Valid usage
[ReplaceableNamedProperties]
interface Window {
  getter any (DOMString name);
};