// Invalid usage
[ReplaceableNamedProperties=foo]
interface InvalidReplacedNamedPropertiesExtendedAttributeWithArgument {
  getter any (in DOMString name);
};

[ReplaceableNamedProperties]
dictionary InvalidReplacedNamedPropertiesExtendedAttributeUsedOnDictionary {
};

[ReplaceableNamedProperties]
interface InvalidReplacedNamedPropertiesExtendedAttributeUsedWithASetter {
  getter any (in DOMString name);
  setter void (in DOMString propertyName, in float propertyValue);
};

[ReplaceableNamedProperties, OverrideBuiltins]
interface InvalidReplacedNamedPropertiesExtendedAttributeUsedWithOverrideBuiltins {
  getter any (in DOMString name);
};


// Valid usage
[ReplaceableNamedProperties]
interface Window {
  getter any (in DOMString name);
};