typedef sequence<double> SequenceInDisguise;

interface WithSequenceAttribute {
  attribute SequenceInDisguise badDisguisedSequenceAttribute; 
  void methodWithSequenceParam(sequence<double> ok);
};


interface WithoutSequenceAttribute {
  attribute double normalAttribute;
};