typedef sequence<float> SequenceInDisguise;

interface WithSequenceAttribute {
  attribute SequenceInDisguise badDisguisedSequenceAttribute; 
  void methodWithSequenceParam(sequence<float> ok);
};


interface WithoutSequenceAttribute {
  attribute float normalAttribute;
};