[TreatNonCallableAsNull]
interface BogusTreatNonCallableAsNullUsedOnInterface {
};

interface BogusEventHandler {
  void eventOccurred(DOMString details);
};


interface BogusTreatNonCallableAsNullUsedOnAttributeWhoseTypeIsNotCallback {
  [TreatNonCallableAsNull] attribute EventHandler handler;
  [TreatNonCallableAsNull] attribute BogusEventHandler? handler2;
};


callback interface EventHandler {
  void eventOccurred(DOMString details);
};

interface Manager {
  attribute EventHandler? handler1;
  [TreatNonCallableAsNull] attribute EventHandler? handler2;
  [TreatNonCallableAsNull] attribute Function? handler3;
  void handler([TreatNonCallableAsNull] EventHandler? handler);
};
