/* TreatNullAs only appear on attributes or operations arguments */
[TreatNullAs]
interface BogusTreatNullAsInterface {};

/* TreatNullAs only appear on attributes or operations arguments with DOMString type */
interface BogusTreatNullAsOnNonDOMStringType {
  [TreatNullAs=String] attribute long counter;
};

/* TreatNullAs requires an argument */
interface BogusTreatNullAsArgument {
  [TreatNullAs] attribute DOMString name;
};

/* TreatNullAs requires String as argument */
interface BogusTreatNullAsNoArgument {
  [TreatNullAs=EmptyString] DOMString bar();
};

/* TreatNullAs only applies to non-nullable DOMString */
interface BogusNullableDOMStringType {
  [TreatNullAs=String] attribute DOMString? onAttribute;
};


/* Valid usage of TreatNullAs */
interface ValidTreatNullAs {
  [TreatNullAs=String] attribute DOMString onAttribute;
  [TreatNullAs=String] DOMString onOperation(long bar);
  boolean onOperationArgument([TreatNullAs=String] DOMString bar);
};